version: "3.9"
services:
  base-server:
    container_name: base-server
    image: "docker.io/library/base-server:${EASY_CHAT_HOME_VERSION}"
    ports:
      - 3000:3000
#    environment:
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
